name: Brewski
url: https://github.com/Loong-T/hexo-theme-brewski

menu:
  Home: /
  Archives: /archives
  RSS: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Disqus shortname
disqus:

# Waline
waline:
  server_url: 
  placeholder: 

# Analytics
google_analytics: 

# Copyright Infomation
copyright:
  since: 
  name: 
  url: 
